name: myERP Developers
markdown: redcarpet
safe: true
lsi: false
highlighter: pygments

api:
  v1: /v1
  base_url: https://api.myerp.com
  auth_pattern: -u "email:api-key"
  batch_limit: 25

resource:
  customers:
    url: /customers
  vendors:
    url: /vendors
  projects:
    url: /projects
  sales_orders:
    url: /sales_orders
  items:
    url: /items
  payment_terms:
    url: /payment_terms
  item_families:
    url: /item_families
  currencies:
    url: /currencies
  transactions:
    url: /transactions
  accounts:
    url: /accounts
  units:
    url: /units
  taxes:
    url: /taxes
  bank_entries:
    url: /bank_entries

format:
  date: yyyy-MM-dd (e.g. 2013-06-26)
  type:
    string: string
    integer: integer
    double: double
    boolean: boolean
    date: date
    address: '<a href="/docs/1.0/api/#address" alt=""/>Address</a>'
    contact: 'array[<a href="/docs/1.0/api/#contact" alt=""/>Contact</a>]'
    order_line: '<a href="/docs/1.0/api/order_line/#format" alt=""/>Order Line</a>'
    entry: '<a href="/docs/1.0/api/#entry" alt=""/>Entry</a>'
