name: MyERP Developers
markdown: redcarpet
safe: true
lsi: false
pygments: true

api:
  v1: /v1     
  base_url: http://app.myerp.com/api
  auth_pattern: -u "email:api-key"
  
resource:
  accounts:
    url: /accounts
  contacts:
    url: /contacts
  projects:
    url: /projects
  sales_orders:
    url: /sales_orders
  order_lines:
    url: /order_lines
  items:
    url: /items
  payment_terms:
    url: /payment_terms
  item_families:
    url: /item_families
  currencies:
    url: /currencies
  accounting_transactions:
    url: /accounting_transactions

format:
  header:
    field_name: Field Name
    description: Description
    type: Type
    values: Values
    default: Default
    non_editable: Non editable
  type:
    string: '"String":/docs/1.0/glossary/#string'
    string4: '"String ^4^":/docs/1.0/glossary/#string4'
    string10: '"String ^10^":/docs/1.0/glossary/#string10'
    string64: '"String ^64^":/docs/1.0/glossary/#string64'
    string128: '"String ^128^":/docs/1.0/glossary/#string128'
    string255: '"String ^255^":/docs/1.0/glossary/#string255'
    text: '"Text":/docs/1.0/glossary/#text'
    integer: '"Integer":/docs/1.0/glossary/#integer'
    long: '"Long":/docs/1.0/glossary/#long'
    double: '"Double":/docs/1.0/glossary/#double'
    boolean: '"Boolean":/docs/1.0/glossary/#boolean'
    date: '"Date":/docs/1.0/glossary/#date'
    address: '"Address":/docs/1.0/api/address/#format'
    account_contact: '"Account Contact":/docs/1.0/api/account_contact/#format'
    order_line: '"Order Line":/docs/1.0/api/order_line/#format'
    accounting_entry: '"Accounting Entry":/docs/1.0/api/accounting_entry/#format'
  mandatory: Mandatory
  non_editable: X
  non_available: '-'
  read_only: Read only
  