name: myERP Developers
markdown: redcarpet
safe: true
lsi: false
pygments: true

api:
  v1: /v1
  base_url: https://app.myerp.com/api
  auth_pattern: -u "email:api-key"
  batch_limit: 25

resource:
  customers:
    url: /customers
  vendors:
    url: /vendors
  projects:
    url: /projects
  sales_orders:
    url: /sales_orders
  items:
    url: /items
  payment_terms:
    url: /payment_terms
  item_families:
    url: /item_families
  currencies:
    url: /currencies
  transactions:
    url: /transactions
  accounts:
    url: /accounts
  units:
    url: /units
  taxes:
    url: /taxes

format:
  header:
    field_name: Field Name
    description: Description
    type: Type
    values: Values
    default: Default
    non_editable: Non editable
  type:
    string: '"String":/docs/1.0/glossary/#string'
    string4: '"String ^4^":/docs/1.0/glossary/#string4'
    string10: '"String ^10^":/docs/1.0/glossary/#string10'
    string64: '"String ^64^":/docs/1.0/glossary/#string64'
    string128: '"String ^128^":/docs/1.0/glossary/#string128'
    string255: '"String ^255^":/docs/1.0/glossary/#string255'
    text: '"Text":/docs/1.0/glossary/#text'
    integer: '"Integer":/docs/1.0/glossary/#integer'
    long: '"Long":/docs/1.0/glossary/#long'
    double: '"Double":/docs/1.0/glossary/#double'
    boolean: '"Boolean":/docs/1.0/glossary/#boolean'
    date: '"Date":/docs/1.0/glossary/#date'
    address: '"Address":/docs/1.0/api/address/#format'
    contact: '"Contact":/docs/1.0/api/contact/#format'
    order_line: '"Order Line":/docs/1.0/api/order_line/#format'
    entry: '"Entry":/docs/1.0/api/entry/#format'
  mandatory: Mandatory
  non_editable: X
  non_available: '-'
  read_only: Read only
