name: MyERP Developers
markdown: redcarpet
safe: true
lsi: false
pygments: true

api:
  v1: /v1     
  base_url: http://app.myerp.com/api
  auth_pattern: -u "email:api-key"
  
resource:
  account:
    url: /account/
  accounts:
    url: /accounts
  account_contact:
    url: /account_contact/
  account_contacts:
    url: /account_contacts
  project:
    url: /project/

format:
  header:
    field_name: Field Name
    description: Description
    type: Type
    values: Values
    default: Default
    non_editable: Non editable
  type:
    string: '"String":/docs/1.0/glossary/#string'
    string4: '"String ^4^":/docs/1.0/glossary/#string4'
    string10: '"String ^10^":/docs/1.0/glossary/#string10'
    string64: '"String ^64^":/docs/1.0/glossary/#string64'
    string128: '"String ^128^":/docs/1.0/glossary/#string128'
    string255: '"String ^255^":/docs/1.0/glossary/#string255'
    text: '"Text":/docs/1.0/glossary/#text'
    integer: '"Integer":/docs/1.0/glossary/#integer'
    long: '"Long":/docs/1.0/glossary/#long'
    boolean: '"Boolean":/docs/1.0/glossary/#boolean'
    address: '"Address":/docs/1.0/api/address/#format'
    account_contact: '"Account Contact":docs/1.0/api/account_contact/#format'
  mandatory: Mandatory
  non_editable: X
  non_available: '-'
  read_only: Read only
  