name: MyERP Developers
markdown: redcarpet
safe: true
lsi: false
pygments: true

api:
  v1: /v1     
  base_url: http://app.myerp.com/api
  auth_pattern: -u "email:api-key"
  
resource:
  account:
    url: /account/
  accounts:
    url: /accounts

format:
  header:
    field_name: Field Name
    description: Description
    type: Type
    values: Values
    default: Default
    non_editable: Non editable
  type:
    string: '"String":../../glossary/#string'
    string4: '"String ^4^":../../glossary/#string4'
    string64: '"String ^64^":../../glossary/#string64'
    string255: '"String ^255^":../../glossary/#string255'
    text: '"Text":../../glossary/#text'
    integer: '"Integer":../../glossary/#integer'
    long: '"Long":../../glossary/#long'
    boolean: '"Boolean":../../glossary/#boolean'
    address: Address
    account_contact: Account Contact
  mandatory: Mandatory
  non_editable: X
  non_available: '-'
  