name: OneUp Developers
markdown: redcarpet
safe: true
lsi: false
highlighter: rouge

api:
  v1: /v1
  base_url: https://api.oneup.com
  auth_pattern: -u "email:api-key"
  bulk_deletion_limit: 50

resource:
  customers:
    url: /customers
  vendors:
    url: /vendors
  projects:
    url: /projects
  sales_orders:
    url: /sales_orders
  invoices:
    url: /invoices
  payments:
    url: /payments
  items:
    url: /items
  payment_terms:
    url: /payment_terms
  item_families:
    url: /item_families
  currencies:
    url: /currencies
  transactions:
    url: /transactions
  journals:
    url: /journals
  accounts:
    url: /accounts
  units:
    url: /units
  taxes:
    url: /taxes
  bank_entries:
    url: /bank_entries
  bank_accounts:
    url: /bank_accounts
  opportunity_tasks:
    url: /opportunity_tasks
  project_tasks:
    url: /project_tasks
  calls:
    url: /calls

format:
  date: yyyy-MM-dd (e.g. 2013-06-26)
  type:
    string: string
    integer: integer
    double: double
    boolean: boolean
    date: date
    object: object
    address: '<a href="/docs/1.0/api/#address" alt=""/>Address</a>'
    payment_terms: '<a href="/docs/1.0/api/#paymentterm" alt=""/>Payment Terms</a>'
    tax: '<a href="/docs/1.0/api/#tax" alt=""/>Tax</a>'
    contact: 'array[<a href="/docs/1.0/api/#contact" alt=""/>Contact</a>]'
    order_line: 'array[<a href="/docs/1.0/api/#orderline" alt=""/>Order Line</a>]'
    entry: 'array[<a href="/docs/1.0/api/#entry" alt=""/>Entry</a>]'
    journal: '<a href="/docs/1.0/api/#journal" alt=""/>Journal</a>'
