name: myERP Developers
markdown: redcarpet
safe: true
lsi: false
highlighter: pygments

api:
  v1: /v1
  base_url: https://api.myerp.com
  auth_pattern: -u "email:api-key"
  batch_limit: 25

resource:
  customers:
    url: /customers
  vendors:
    url: /vendors
  projects:
    url: /projects
  sales_orders:
    url: /sales_orders
  items:
    url: /items
  payment_terms:
    url: /payment_terms
  item_families:
    url: /item_families
  currencies:
    url: /currencies
  transactions:
    url: /transactions
  accounts:
    url: /accounts
  units:
    url: /units
  taxes:
    url: /taxes

format:
  type:
    string: '<a href="/docs/1.0/overview/#string" alt=""/>string</a>'
    integer: '<a href="/docs/1.0/overview/#integer" alt=""/>integer</a>'
    double: '<a href="/docs/1.0/overview/#double" alt=""/>double</a>'
    boolean: '<a href="/docs/1.0/overview/#boolean" alt=""/>boolean</a>'
    date: '<a href="/docs/1.0/overview/#date" alt=""/>date</a>'
    address: '<a href="/docs/1.0/api/address/#format" alt=""/>Address</a>'
    contact: '<a href="/docs/1.0/api/contact/#format" alt=""/>Contact</a>'
    order_line: '<a href="/docs/1.0/api/order_line/#format" alt=""/>Order Line</a>'
    entry: '<a href="/docs/1.0/api/entry/#format" alt=""/>Entry</a>'
