name: OneUp Developers
markdown: redcarpet
safe: true
lsi: false
highlighter: rouge

api:
  v1: /v1
  base_url: https://api.oneup.com
  auth_pattern: -u "email:api-key"
  bulk_deletion_limit: 50

resource:
  customers:
    url: /customers
  vendors:
    url: /vendors
  projects:
    url: /projects
  sales_orders:
    url: /sales_orders
  quotes:
    url: /quotes
  invoices:
    url: /invoices
  installments:
    url: /installments
  payments:
    url: /payments
  credit_memos:
    url: /credit_memos
  items:
    url: /items
  payment_terms:
    url: /payment_terms
  item_families:
    url: /item_families
  currencies:
    url: /currencies
  transactions:
    url: /transactions
  journals:
    url: /journals
  accounts:
    url: /accounts
  units:
    url: /units
  taxes:
    url: /taxes
  bank_entries:
    url: /bank_entries
  bank_accounts:
    url: /bank_accounts
  opportunity_tasks:
    url: /opportunity_tasks
  project_tasks:
    url: /project_tasks
  cash_flow_details:
    url: /dashboards/accounting/cash_flow/details
  cash_flow_overtime:
    url: /dashboards/accounting/cash_flow/overtime
  profit_loss_kpi:
    url: /dashboards/accounting/profit_loss/kpi
  expense_breakdown:
    url: /dashboards/accounting/expense/breakdown
  sales_goal:
    url: /dashboards/sales/sales/goal
  sales_overtime:
    url: /dashboards/sales/sales/overtime
  sales_top_customers:
    url: /dashboards/sales/top_customers
  sales_top_invoiced:
    url: /dashboards/sales/top_invoiced_items
  domains:
    url: /domains

format:
  date: yyyy-MM-dd (e.g. 2013-06-26)
  type:
    string: string
    integer: integer
    double: double
    boolean: boolean
    date: date
    object: object
    objects: array[object]
    address: '<a href="/docs/1.0/api/#address" alt=""/>Address</a>'
    customer: '<a href="/docs/1.0/api/#customer" alt=""/>Customer</a>'
    payment_terms: '<a href="/docs/1.0/api/#paymentterm" alt=""/>Payment Terms</a>'
    tax: '<a href="/docs/1.0/api/#tax" alt=""/>Tax</a>'
    contact: 'array[<a href="/docs/1.0/api/#contact" alt=""/>Contact</a>]'
    order_line: 'array[<a href="/docs/1.0/api/#orderline" alt=""/>Order Line</a>]'
    entry: 'array[<a href="/docs/1.0/api/#entry" alt=""/>Entry</a>]'
    journal: '<a href="/docs/1.0/api/#journal" alt=""/>Journal</a>'
    account: '<a href="/docs/1.0/api/#account" alt=""/>Account</a>'
    documents: 'array[<a href="/docs/1.0/api/#document" alt=""/>Document</a>]'
    sales_documents: 'array[<a href="/docs/1.0/api/#sales_document" alt=""/>Sales document</a>]'
    kpis: 'array[<a href="/docs/1.0/api/#cash_flow_detail_kpi" alt=""/>KPI</a>]'
    expenses: 'array[<a href="/docs/1.0/api/#expense" alt=""/>Expense</a>]'
    progress: '<a href="/docs/1.0/api/#progress" alt=""/>Progress</a>'
    periods: '<a href="/docs/1.0/api/#cash_flow_overtime_periods" alt=""/>Periods</a>'
    top_customers: 'array[<a href="/docs/1.0/api/#top_customer" alt=""/>Top customer</a>]'
    top_invoiced: 'array[<a href="/docs/1.0/api/#top_invoiced" alt=""/>Top invoiced</a>]'
    snippet: '<a href="/docs/1.0/api/#snippet" title="">Snippet</a>'
